### ISSUE TITLE
ArticleAction - for blog page

### ISSUE THREAD

**Issue by FranckPiazza** [wearemetabolism/wordpress-bundle#17]
Hi, I do not find the way to call the articleAction function for the blog page.

The Front and blog page and set in the reading wp backend.

The frontAction load correctly like this ,
`if( is_user_logged_in() ){
            $context->add('section', 'Homepage for logged in user');
        }
        $context->add('section', 'Homepage');
        return $this->render('homepage.html.twig', $context->toArray());`

but not the  articleAction

`public function articleAction(Context $context)
    {
        $context->add('section', 'article');
        $context->addPosts(['category__and' => [1,3], 'posts_per_page' => 2, 'orderby' => 'title'], 'portraits');
        $context->addSitemap();
       $context->addPagination();
        return $this->render('page/articles.html.twig', $context->toArray());
    }`

I need to use a function like this in the blog controller to check if the page is the blog page 

`function is_blog () {
        global  $post;
        $posttype = get_post_type($post );
        return ( ((is_archive()) || (is_author()) || (is_category()) || (is_home()) || (is_single()) || (is_tag())) && ( $posttype == 'post')  ) ? true : false ;
    }`

I have miss something ?

There is not the is_blog_page in the debug context
![image](https://user-images.githubusercontent.com/1138310/124741967-8a760200-df1c-11eb-86e2-ac34bd3c8f0a.png)

Regards

**Comment by jerome-barbato** [comment]
Hi ! 

The pages and the blog articles will run the same "pageAction", that's because the route definition is the same for article and page ( /{slug} ) witch is odd but it's Wordpress way.

We usually never use the default Wordpress article post type, we create a new cpt so we could have a custom route structure ( also better for seo ) but if you still want to use it, in the pageAction controller, you can use $post->type to know if it's a "page" or "post"

Is it clear enough ?

**Comment by FranckPiazza** [comment]
Perfect ;)
